terminal_source: ''
software_timer:
  priority: 2
  stack_depth: 512
SPI:
  spi1:
    dma_enable_min_size: 3
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: ''
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
    dma_section: ''
ADC:
  adc1:
    buffer_size: 128
    vref: 3.3
    dma_section: ''
USB:
  tx_queue_size: 5
Terminal:
  READ_BUFF_SIZE: 32
  MAX_LINE_SIZE: 32
  MAX_ARG_NUMBER: 5
  MAX_HISTORY_NUMBER: 5
SYSTEM: None
device_aliases:
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  LED:
    type: GPIO
    aliases:
    - LED
  pwm_tim2_ch3:
    type: PWM
    aliases:
    - pwm_tim2_ch3
  adc1_adc_channel_0:
    type: ADC
    aliases:
    - adc1_adc_channel_0
  spi1:
    type: SPI
    aliases:
    - spi1
  usart1:
    type: UART
    aliases:
    - usart1
  uart_cdc:
    type: UART
    aliases:
    - uart_cdc
FlashLayout:
  model: STM32F103RCT6
  flash_base: '0x08000000'
  flash_size_kb: 256
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 2.0
  - index: 1
    address: '0x08000800'
    size_kb: 2.0
  - index: 2
    address: '0x08001000'
    size_kb: 2.0
  - index: 3
    address: '0x08001800'
    size_kb: 2.0
  - index: 4
    address: '0x08002000'
    size_kb: 2.0
  - index: 5
    address: '0x08002800'
    size_kb: 2.0
  - index: 6
    address: '0x08003000'
    size_kb: 2.0
  - index: 7
    address: '0x08003800'
    size_kb: 2.0
  - index: 8
    address: '0x08004000'
    size_kb: 2.0
  - index: 9
    address: '0x08004800'
    size_kb: 2.0
  - index: 10
    address: '0x08005000'
    size_kb: 2.0
  - index: 11
    address: '0x08005800'
    size_kb: 2.0
  - index: 12
    address: '0x08006000'
    size_kb: 2.0
  - index: 13
    address: '0x08006800'
    size_kb: 2.0
  - index: 14
    address: '0x08007000'
    size_kb: 2.0
  - index: 15
    address: '0x08007800'
    size_kb: 2.0
  - index: 16
    address: '0x08008000'
    size_kb: 2.0
  - index: 17
    address: '0x08008800'
    size_kb: 2.0
  - index: 18
    address: '0x08009000'
    size_kb: 2.0
  - index: 19
    address: '0x08009800'
    size_kb: 2.0
  - index: 20
    address: '0x0800A000'
    size_kb: 2.0
  - index: 21
    address: '0x0800A800'
    size_kb: 2.0
  - index: 22
    address: '0x0800B000'
    size_kb: 2.0
  - index: 23
    address: '0x0800B800'
    size_kb: 2.0
  - index: 24
    address: '0x0800C000'
    size_kb: 2.0
  - index: 25
    address: '0x0800C800'
    size_kb: 2.0
  - index: 26
    address: '0x0800D000'
    size_kb: 2.0
  - index: 27
    address: '0x0800D800'
    size_kb: 2.0
  - index: 28
    address: '0x0800E000'
    size_kb: 2.0
  - index: 29
    address: '0x0800E800'
    size_kb: 2.0
  - index: 30
    address: '0x0800F000'
    size_kb: 2.0
  - index: 31
    address: '0x0800F800'
    size_kb: 2.0
  - index: 32
    address: '0x08010000'
    size_kb: 2.0
  - index: 33
    address: '0x08010800'
    size_kb: 2.0
  - index: 34
    address: '0x08011000'
    size_kb: 2.0
  - index: 35
    address: '0x08011800'
    size_kb: 2.0
  - index: 36
    address: '0x08012000'
    size_kb: 2.0
  - index: 37
    address: '0x08012800'
    size_kb: 2.0
  - index: 38
    address: '0x08013000'
    size_kb: 2.0
  - index: 39
    address: '0x08013800'
    size_kb: 2.0
  - index: 40
    address: '0x08014000'
    size_kb: 2.0
  - index: 41
    address: '0x08014800'
    size_kb: 2.0
  - index: 42
    address: '0x08015000'
    size_kb: 2.0
  - index: 43
    address: '0x08015800'
    size_kb: 2.0
  - index: 44
    address: '0x08016000'
    size_kb: 2.0
  - index: 45
    address: '0x08016800'
    size_kb: 2.0
  - index: 46
    address: '0x08017000'
    size_kb: 2.0
  - index: 47
    address: '0x08017800'
    size_kb: 2.0
  - index: 48
    address: '0x08018000'
    size_kb: 2.0
  - index: 49
    address: '0x08018800'
    size_kb: 2.0
  - index: 50
    address: '0x08019000'
    size_kb: 2.0
  - index: 51
    address: '0x08019800'
    size_kb: 2.0
  - index: 52
    address: '0x0801A000'
    size_kb: 2.0
  - index: 53
    address: '0x0801A800'
    size_kb: 2.0
  - index: 54
    address: '0x0801B000'
    size_kb: 2.0
  - index: 55
    address: '0x0801B800'
    size_kb: 2.0
  - index: 56
    address: '0x0801C000'
    size_kb: 2.0
  - index: 57
    address: '0x0801C800'
    size_kb: 2.0
  - index: 58
    address: '0x0801D000'
    size_kb: 2.0
  - index: 59
    address: '0x0801D800'
    size_kb: 2.0
  - index: 60
    address: '0x0801E000'
    size_kb: 2.0
  - index: 61
    address: '0x0801E800'
    size_kb: 2.0
  - index: 62
    address: '0x0801F000'
    size_kb: 2.0
  - index: 63
    address: '0x0801F800'
    size_kb: 2.0
  - index: 64
    address: '0x08020000'
    size_kb: 2.0
  - index: 65
    address: '0x08020800'
    size_kb: 2.0
  - index: 66
    address: '0x08021000'
    size_kb: 2.0
  - index: 67
    address: '0x08021800'
    size_kb: 2.0
  - index: 68
    address: '0x08022000'
    size_kb: 2.0
  - index: 69
    address: '0x08022800'
    size_kb: 2.0
  - index: 70
    address: '0x08023000'
    size_kb: 2.0
  - index: 71
    address: '0x08023800'
    size_kb: 2.0
  - index: 72
    address: '0x08024000'
    size_kb: 2.0
  - index: 73
    address: '0x08024800'
    size_kb: 2.0
  - index: 74
    address: '0x08025000'
    size_kb: 2.0
  - index: 75
    address: '0x08025800'
    size_kb: 2.0
  - index: 76
    address: '0x08026000'
    size_kb: 2.0
  - index: 77
    address: '0x08026800'
    size_kb: 2.0
  - index: 78
    address: '0x08027000'
    size_kb: 2.0
  - index: 79
    address: '0x08027800'
    size_kb: 2.0
  - index: 80
    address: '0x08028000'
    size_kb: 2.0
  - index: 81
    address: '0x08028800'
    size_kb: 2.0
  - index: 82
    address: '0x08029000'
    size_kb: 2.0
  - index: 83
    address: '0x08029800'
    size_kb: 2.0
  - index: 84
    address: '0x0802A000'
    size_kb: 2.0
  - index: 85
    address: '0x0802A800'
    size_kb: 2.0
  - index: 86
    address: '0x0802B000'
    size_kb: 2.0
  - index: 87
    address: '0x0802B800'
    size_kb: 2.0
  - index: 88
    address: '0x0802C000'
    size_kb: 2.0
  - index: 89
    address: '0x0802C800'
    size_kb: 2.0
  - index: 90
    address: '0x0802D000'
    size_kb: 2.0
  - index: 91
    address: '0x0802D800'
    size_kb: 2.0
  - index: 92
    address: '0x0802E000'
    size_kb: 2.0
  - index: 93
    address: '0x0802E800'
    size_kb: 2.0
  - index: 94
    address: '0x0802F000'
    size_kb: 2.0
  - index: 95
    address: '0x0802F800'
    size_kb: 2.0
  - index: 96
    address: '0x08030000'
    size_kb: 2.0
  - index: 97
    address: '0x08030800'
    size_kb: 2.0
  - index: 98
    address: '0x08031000'
    size_kb: 2.0
  - index: 99
    address: '0x08031800'
    size_kb: 2.0
  - index: 100
    address: '0x08032000'
    size_kb: 2.0
  - index: 101
    address: '0x08032800'
    size_kb: 2.0
  - index: 102
    address: '0x08033000'
    size_kb: 2.0
  - index: 103
    address: '0x08033800'
    size_kb: 2.0
  - index: 104
    address: '0x08034000'
    size_kb: 2.0
  - index: 105
    address: '0x08034800'
    size_kb: 2.0
  - index: 106
    address: '0x08035000'
    size_kb: 2.0
  - index: 107
    address: '0x08035800'
    size_kb: 2.0
  - index: 108
    address: '0x08036000'
    size_kb: 2.0
  - index: 109
    address: '0x08036800'
    size_kb: 2.0
  - index: 110
    address: '0x08037000'
    size_kb: 2.0
  - index: 111
    address: '0x08037800'
    size_kb: 2.0
  - index: 112
    address: '0x08038000'
    size_kb: 2.0
  - index: 113
    address: '0x08038800'
    size_kb: 2.0
  - index: 114
    address: '0x08039000'
    size_kb: 2.0
  - index: 115
    address: '0x08039800'
    size_kb: 2.0
  - index: 116
    address: '0x0803A000'
    size_kb: 2.0
  - index: 117
    address: '0x0803A800'
    size_kb: 2.0
  - index: 118
    address: '0x0803B000'
    size_kb: 2.0
  - index: 119
    address: '0x0803B800'
    size_kb: 2.0
  - index: 120
    address: '0x0803C000'
    size_kb: 2.0
  - index: 121
    address: '0x0803C800'
    size_kb: 2.0
  - index: 122
    address: '0x0803D000'
    size_kb: 2.0
  - index: 123
    address: '0x0803D800'
    size_kb: 2.0
  - index: 124
    address: '0x0803E000'
    size_kb: 2.0
  - index: 125
    address: '0x0803E800'
    size_kb: 2.0
  - index: 126
    address: '0x0803F000'
    size_kb: 2.0
  - index: 127
    address: '0x0803F800'
    size_kb: 2.0
